<?php

namespace ElementPack\Includes\TemplateLibrary\Editor\Manager;

defined( 'ABSPATH' ) || exit;

/**
 * Progress state for a single template import.
 *
 * The import itself runs inside one blocking AJAX request, so it cannot report
 * back to the browser as it works. Instead it writes its state here, and the
 * editor polls a separate endpoint to read it while that request is still open.
 */
class Import_Progress {

	const TRANSIENT_PREFIX = 'ep_tpl_import_progress_';

	/**
	 * Long enough to outlive a slow image-heavy import, short enough that an
	 * abandoned import cleans up after itself.
	 */
	const TTL = 15 * MINUTE_IN_SECONDS;

	/**
	 * @var string Sanitized import id, or '' when no id was supplied.
	 */
	private $id;

	/**
	 * @var array|null Last state handed to set_transient(), for write throttling.
	 */
	private $last_written = null;

	public function __construct( $id = '' ) {
		$this->id = self::sanitize_id( $id );
	}

	/**
	 * The id is generated by the browser, so treat it as untrusted: it is only
	 * ever used to build a transient key.
	 */
	public static function sanitize_id( $id ) {
		return substr( preg_replace( '/[^A-Za-z0-9]/', '', (string) $id ), 0, 32 );
	}

	/**
	 * An import with no id still runs, it just reports nothing.
	 */
	public function is_enabled() {
		return '' !== $this->id;
	}

	private static function key( $id ) {
		return self::TRANSIENT_PREFIX . $id;
	}

	public function update( $stage, $percent, array $extra = [] ) {
		if ( ! $this->is_enabled() ) {
			return;
		}

		$state = array_merge(
			[
				'stage'   => $stage,
				'percent' => max( 0, min( 100, (int) $percent ) ),
			],
			$extra
		);

		// The element loop calls this once per element. Skip the write unless
		// something the browser can actually see has changed.
		if ( $this->last_written === $state ) {
			return;
		}

		$this->last_written = $state;

		set_transient( self::key( $this->id ), $state, self::TTL );
	}

	/**
	 * @return array|false State array, or false if nothing has been written yet.
	 */
	public static function read( $id ) {
		$id = self::sanitize_id( $id );

		if ( '' === $id ) {
			return false;
		}

		return get_transient( self::key( $id ) );
	}

	public function clear() {
		if ( ! $this->is_enabled() ) {
			return;
		}

		$this->last_written = null;

		delete_transient( self::key( $this->id ) );
	}
}
